### ISSUE TITLE
Problems with Wayland on Linux

### ISSUE THREAD

**Issue by lavilao** [Willy-JL/F95Checker#132] opened 2024-02-16 14:43 UTC
Hi, everytime I try to run f95checker on crostini it throws errors about the opengl context:
```
./F95Checker-Debug 
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: No shell integration named "qt-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells QList("xdg-shell", "wl-shell", "ivi-shell", "qt-shell")
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/cx_Freeze/initscripts/__startup__.py", line 124, in run
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/cx_Freeze/initscripts/console.py", line 16, in run
  File "/home/runner/work/F95Checker/F95Checker/main-debug.py", line 89, in <module>
  File "/home/runner/work/F95Checker/F95Checker/main-debug.py", line 39, in main
  File "/home/runner/work/F95Checker/F95Checker/modules/gui.py", line 379, in __init__
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/imgui/integrations/glfw.py", line 12, in __init__
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/imgui/integrations/opengl.py", line 60, in __init__
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/imgui/integrations/base.py", line 17, in __init__
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/imgui/integrations/opengl.py", line 125, in _create_device_objects
  File "src/latebind.pyx", line 51, in OpenGL_accelerate.latebind.Curry.__call__
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 469, in glVertexAttribPointer
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/OpenGL/contextdata.py", line 58, in setValue
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/OpenGL/contextdata.py", line 40, in getContext
OpenGL.error.Error: Attempt to retrieve context when no valid context
```
if I try the wayland backend: 
```
QT_QPA_PLATFORM=wayland ./F95Checker-Debug 
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: No shell integration named "qt-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells QList("xdg-shell", "wl-shell", "ivi-shell", "qt-shell")
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.
```
Do you know what can be done? Thanks in advice!

**Comment by lavilao** [comment] 2024-02-26 01:42
fixed by adding ```XDG_SESSION_TYPE=x11``` and ```QT_QPA_PLATFORM=xcb```

**Comment by Willy-JL** [comment] 2024-09-04 18:19
the Qt part of the issue should be fixed in new beta builds, as i included qt wayland plugins, but glfw and opengl seem to still be an issue as reported on the forum

**Comment by lavilao** [comment] 2024-09-07 02:08
Hi, my previous solution worked on debian but when I changed the container to archlinux I had to use ```QTWEBENGINE_DISABLE_HARDWARE_ACCELERATION=1 QT_QPA_PLATFORM=xcb XDG_SESSION_TYPE=x11 ./F95Checker-Debug```

**Comment by Willy-JL** [comment] 2024-11-19 04:32
@Ink-Sage @lavilao can you try with latest build? it should include those environment variables by default when running under wayland. i hope to find a proper fix eventually, but this might work for now

**Comment by Willy-JL** [comment] 2024-11-20 02:18
i did more digging. i have arch linux with wayland kde on my laptop and been testing some things.

i tested with the bare minimum example from https://github.com/pyimgui/pyimgui/blob/master/doc/examples/integrations_glfw3.py
it opens fine, but it is not usable: the window does not react to any input, neither mouse or keyboard. however, the window is drawinf fine, i added some text that changes each frame and it is updating on screen, so the issue is mainly with inputs.

theres this issue https://github.com/pyimgui/pyimgui/issues/318 where i found out about PYOPENGL_PLATFORM, but it is already using egl on wayland correctly for me, issue here is with inputs

**Comment by Willy-JL** [comment] 2024-11-20 02:35
i wanna bang my head against a wall lmao. i did `sudo pacman -S glfw` and it works now. looks like ill need to find a way to include the required library files with f95checker

**Comment by Willy-JL** [comment] 2024-11-20 03:08
even more digging. pyglfw ships glfw 3.3.9, my system installed glfw 3.4 when i used my package manager. looks like the issues are due to the older glfw library bundled in pyglfw.

the issue is described here https://github.com/glfw/glfw/issues/2495 and stated in the release notes. unfortunate, but understandable.

**Comment by Ink-Sage** [comment] 2024-11-20 07:11
I can't say for certain that I've done every step correctly, but beta 1241 doesn't launch at all on my setup. It briefly (a single frame) pops up a tab on the taskbar and then immediately disappears with no sign of a window.

I put the beta version in a separate folder in the same location as stable, but didn't change, install, or uninstall anything else. The stable release still functions as expected.

**Comment by Willy-JL** [comment] 2024-11-20 07:26
what does it say in console?

**Comment by Ink-Sage** [comment] 2024-11-20 07:41
Is this what you're looking for?

Unable to import OpenGL.arrays.numpymodule.NumpyHandler: No numpy module present: No module named 'numpy'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/cx_Freeze/initscripts/__startup__.py", line 138, in run
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/cx_Freeze/initscripts/console.py", line 17, in run
  File "/home/runner/work/F95Checker/F95Checker/main.py", line 95, in <module>
  File "/home/runner/work/F95Checker/F95Checker/main.py", line 45, in main
  File "/home/runner/work/F95Checker/F95Checker/modules/gui.py", line 399, in __init__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/imgui/integrations/glfw.py", line 12, in __init__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/imgui/integrations/opengl.py", line 60, in __init__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/imgui/integrations/base.py", line 17, in __init__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/imgui/integrations/opengl.py", line 125, in _create_device_objects
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/OpenGL/latebind.py", line 63, in __call__
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 469, in glVertexAttribPointer
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/OpenGL/contextdata.py", line 58, in setValue
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/OpenGL/contextdata.py", line 40, in getContext
OpenGL.error.Error: Attempt to retrieve context when no valid context

**Comment by Willy-JL** [comment] 2024-11-22 06:26
im hoping that is also due to the outdated glfw library included with pyGLFW currently. i managed to fix the compilation issues that blocked it from being upgraded past 3.3.9 https://github.com/FlorianRhiem/pyGLFW/issues/78 , but might be a while before it becomes widely available. gonna wait to see what the maintainer says, then maybe consider bundling an updated .so in the meantime

**Comment by Willy-JL** [comment] 2024-11-22 20:17
@Ink-Sage i switched to the updated version of pyGLFW, it works nicely on my wayland archlinux laptop without needing any workaround and actually running under wayland, not xwayland. please give build 1278 a shot without the environment variable workaround and let me know how it goes

**Comment by Ink-Sage** [comment] 2024-11-23 05:32
I tested full recheck (single title and all titles), adding a game, launching a game, playing a game, and opening forum pages. Everything seems to work flawlessly, with recheck in particular seemingly going a little faster.

**Comment by lavilao** [comment] 2024-11-25 20:29
Hi, I just downloaded the latest build and tried running it without any env var and got this:
 `./F95Checker-Debug 
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name is not activatable")
Unable to import OpenGL.arrays.numpymodule.NumpyHandler: No numpy module present: No module named 'numpy'
Violación de segmento (core generado)`

**Comment by Willy-JL** [comment] 2024-11-25 20:48
@lavilao what desktop environment are you using?

**Comment by lavilao** [comment] 2024-11-25 21:37
None, am using archlinux inside of crostini (chromeos)

**Comment by Willy-JL** [comment] 2024-11-25 22:33
interesting, i would need to do some hands on testing but i dont have a chromebook. for now, best to continue using the env vars. wayland by itself is working fine now as me and Ink-Sage have found, but looks like your setup is an edge case that Qt doesnt really like. maybe you could get away with having only one of the env vars, so maybe qt tray icon runs in x11 mode and the rest runs under wayland, but im not sure.

**Comment by Willy-JL** [comment] 2024-11-25 22:34
ill consider this fixed for now as support for wayland in general is working, might try to look into your specific situation later on

**Closed** 2024-12-12 08:55 UTC
Labels: bugfix, release-pending
