### ISSUE TITLE
Debian glGetUniformLocation (1, b’Texture\x00’) 'invalid operation' err 1282 result -1 in glfwrenderer setup

### ISSUE THREAD

**Issue by yohudood** [Willy-JL/F95Checker#29] opened 2022-09-18 01:50 UTC
python3 main.py
Unable to load numpy_formathandler accelerator from OpenGL_accelerate
Traceback (most recent call last):
  File "/home/yorickhuizenga/Downloads/f95/F95Checker-Source/main.py", line 79, in <module>
    main()
  File "/home/yorickhuizenga/Downloads/f95/F95Checker-Source/main.py", line 54, in main
    globals.gui = gui.MainGUI()
  File "/home/yorickhuizenga/Downloads/f95/F95Checker-Source/modules/gui.py", line 153, in __init__
    self.impl = GlfwRenderer(self.window)
  File "/usr/local/lib/python3.10/dist-packages/imgui/integrations/glfw.py", line 12, in __init__
    super(GlfwRenderer, self).__init__()
  File "/usr/local/lib/python3.10/dist-packages/imgui/integrations/opengl.py", line 60, in __init__
    super(ProgrammablePipelineRenderer, self).__init__()
  File "/usr/local/lib/python3.10/dist-packages/imgui/integrations/base.py", line 17, in __init__
    self._create_device_objects()
  File "/usr/local/lib/python3.10/dist-packages/imgui/integrations/opengl.py", line 108, in _create_device_objects
    self._attrib_location_tex = gl.glGetUniformLocation(self._shader_handle, "Texture")
  File "src/latebind.pyx", line 51, in OpenGL_accelerate.latebind.Curry.__call__
  File "/home/yorickhuizenga/.local/lib/python3.10/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
  File "/home/yorickhuizenga/.local/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
      err = 1282,
      description = b'invalid operation',
      baseOperation = glGetUniformLocation,
      cArguments = (1, b'Texture\x00'),
      result = -1
)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9fd1003400>

**Comment by Willy-JL** [comment] 2022-09-20 19:23
at a brief glance it looks like the same error that unroot has been having since the beginnings of 9.0... still no clue on the cause, can you check if it works with the prebuilt binaries?

**Comment by yohudood** [comment] 2022-09-22 17:19
[log.txt](https://github.com/Willy-JL/F95Checker/files/9628048/log.txt)

F95Checker-Linux

**Comment by Willy-JL** [comment] 2022-09-22 22:35
Hm, same thing there...

**Comment by Willy-JL** [comment] 2022-11-17 12:25
Tried looking more into it, managed nothing. Made a plea for help in pyimgui/pyimgui#309...

**Comment by Willy-JL** [comment] 2022-11-19 04:26
Should be fixed after [build 731](https://github.com/Willy-JL/F95Checker/actions/runs/3501591622). Went through quite the struggles with unroot: first opengl issues, then libc version mismatches and finally outdated sqlite versions, but that's all been fixed and it seems that the proposed fix with the window hints (3db3167e34e1110fb98e6f92d90e23b29c355da1) actually fixes this issue. try it out for yourself and let me know if it's fixed for you too, I'll mark as pending release in the meantime

**Comment by Willy-JL** [comment] 2022-11-19 05:20
Released in [version 9.5](https://github.com/Willy-JL/F95Checker/releases/tag/9.5)

**Closed by Willy-JL** 2022-11-19 05:20 UTC
Labels: bugfix, release-pending
