### ISSUE TITLE
Download button behavior

### ISSUE THREAD

**Issue by gimpyestrada** [Willy-JL/F95Checker#186] opened 2024-11-21 01:15 UTC
I've noticed that the download buttons on the Downloads tab might need some attention.

I know the gofile button just opens the f95 thread, not sure if that's on purpose.

I recall you adding a middle click that gets the actual URL for Mega.  It looks like it opens a little browser window and then closes and the URL is on the clipboard.  Could you leave the little browser window open so we can just click the download button on the Mega site?

**Comment by gimpyestrada** [comment] 2024-11-21 01:16
Sorry, this is using version 11.0 beta 1241

**Comment by Willy-JL** [comment] 2024-11-21 02:46
hi, unfortunately this is a side effect of moving to a cached api. the forum prevents abuse by bots scanning and taking down links by requiring an account to see links. the cache api i made is not authenticated, so it would make it even easier for links to be taken down. i talked with Sam about this concern, and he agreed that it is best to not include public download links this way. only masked links are exposed to the cache api, since these are opaque and still require an f95zone account (and a captcha too) to convert to the real download link.

see here for the code running on the cache api doing this:
https://github.com/Willy-JL/F95Checker/blob/e15ba7e80117c31b12774f4e5b97496e8930fc4b/indexer/scraper.py#L61-L66

however, i understand that it is not ideal for users to have non-masked download links only link to the thread page. ill try to think of  an alternative solution that still requires an account on clientside, but doesnt expose the links to the open internet.

**Comment by Willy-JL** [comment] 2024-11-21 04:56
ive come up with a rough idea of how to improve this for users without exposing naked links to the open internet, will work on it tomorrow

**Comment by Willy-JL** [comment] 2024-11-22 02:25
@gimpyestrada this is now fixed in build 1270.

the cache api replies with info on how to find the link inside the thread, but doesnt expose the link to the open internet to prevent abuse.
the tool will see this, and when these links are middle clicked it will open a small browser window, which automatically finds the link in the page based on how the cache api described it, then it will copy the url.

as a user, the only difference from past behavior is that instead of immediately copying the link, you get a small popup browser for half a second, similar to how masked links always worked.

if you try this new beta, beware that this new method is not yet in all cached threads, invalidating the whole cache would cause performance issues so this will roll out gradually over the next week as games are updated / cache expires.

**Closed** 2024-11-22 02:26 UTC
Labels: bugfix

**Comment by gimpyestrada** [comment] 2024-12-03 02:16
I saw the new behavior work fine with a gofile link.  I just clicked a Mega link and the app opened and closed the small window, and now it is hung.

**Comment by gimpyestrada** [comment] 2024-12-04 03:15
Nope, I have render when unfocused checked.  I let it sit for a good long time and nothing happened.  I couldn't click anything in the UI anymore, so I killed it.

**Comment by gimpyestrada** [comment] 2024-12-05 00:55
Happened again, something about Mega links. The popup closes but the UI is frozen.

**Comment by Willy-JL** [comment] 2024-12-05 11:40
I just tried multiple times right now, can't replicate. What exact beta build are you on? Are you using normal or debug exe? Windows I assume?

**Comment by Willy-JL** [comment] 2024-12-06 01:00
@gimpyestrada I think i just managed to replicate it, but in another context: if you log out, then trigger a login, and you close it without logging in, it will start consuming as much CPU as possible and the interface will be slow or unresponsive. Just finished debugging this, and as often happens it's not something i did wrong. For some reason, asyncio subprocess loop on windows is not setting the process return code when it exits. The logic to get data from the web view checks the return code to know if the process is still alive, and this return code is never set, so it keeps trying to talk to a dead process.
I've found an alternative that works: checking if the stdout handle is at EOF. I'll check both the return code and stdout EOF just to be sure.
Can you confirm if the behavior you experienced is the same when logging in and closing the window without logging in? I still can't replicate the issue from download links but i assume it's a race condition that triggers this return code bug, while the login window closing always triggers it without chance of succeeding.
Also I'll push a build with this issue fixed very shortly, please test if the problem is fixed there.

**Comment by gimpyestrada** [comment] 2024-12-06 03:45
Not sure what you mean by close the window without logging in.  I can tell you that when I hit the issue I hear my CPU fan ramp up, so I bet it's the same.

**Comment by Willy-JL** [comment] 2024-12-06 13:04
Yeah it should be the same then. I meant you clear your cookies in manage > clear, then you try to check notifications for example which brings up a window to login, then close those small window without logging in. But yeah sounds like the same behavior, it's fixed in new beta.
