### ISSUE TITLE
Can't Full Recheck Any Games on Linux (Nobara)

### ISSUE THREAD

**Issue by Ink-Sage** [Willy-JL/F95Checker#167] opened 2024-08-03 22:20 UTC
When trying to do the initial check after adding games, the progress starts at 0% and stays there. It never proceeds, leading to me inevitably cancelling it.

When using this program on a prior windows install, it worked flawlessly, but it seems to not want to check any games with this fresh install of Nobara.

![Screenshot_20240803_180632](https://github.com/user-attachments/assets/5f5c57c6-50f7-4058-a0d6-2039301679a7)

As seen in the above screenshot, this is what happens when I trigger a refresh or full recheck. Even after leaving it for half an hour, it still stays at 0%.

After launching the program and triggering a refresh, this is the log file:
[log.txt](https://github.com/user-attachments/files/16483062/log.txt)

**Comment by Ink-Sage** [comment] 2024-08-17 04:16
Issue resolved. For anyone in a similar position, I found this on the F95 forum for this tool.

Create a powershell script with the following lines:
#!/bin/bash
export XDG_SESSION_TYPE=x11
export QT_QPA_PLATFORM=xcb
./F95Checker

After that, run the script inside of your F95Checker install folder and it should launch the program having made the necessary changes. If it successfully checks the games, you know it worked. I recommend restarting the system.

Afterward, you should be able to launch the program like normal, but now the checker should actually work.

**Comment by Willy-JL** [comment] 2024-09-04 18:17
ah, duplicate of #132

**Closed by Willy-JL** 2024-09-04 18:17 UTC
