### ISSUE TITLE
Missing Current Installed Version in F95Checker 11 Beta

### ISSUE THREAD

**Issue by nazdridoy** [Willy-JL/F95Checker#123] opened 2024-02-02 18:38 UTC
**Issue Description:**
I have been testing out the F95Checker 11 Beta and noticed a few changes in the way updates for games are displayed. While I appreciate the efforts in fixing many bugs, there are a couple of aspects that seem to have changed from the previous version (v10.2) that I found to be useful.

1. **Missing Current Installed Version:**
   In the previous version (v10.2), there was a star mark in front of updated games, and users could also see the current installed version and the current update version number. This feature was particularly helpful for users to keep track of their saved game versions or choose to skip updating a game until a specific version. However, in the new version (v11 beta), the current installed version is no longer visible, and all games now display only the updated version number.

*v10.2*
![2024-02-03_00-16](https://github.com/Willy-JL/F95Checker/assets/45564804/f27789ad-4ad5-47e8-8aa5-0a29dbf01f6d)

*v11 beta*
![2024-02-03_00-17](https://github.com/Willy-JL/F95Checker/assets/45564804/ca6e53d5-4710-4419-bf67-21ac9afebc26)

2. **Update Icon:**
 Another observation is that all games now have a shootingStar icon at the end of the name. Previously, this icon was associated only with updated games. It might be helpful to distinguish between games that have received updates and those that haven't to provide users with a clearer overview.

![2024-02-03_00-22](https://github.com/Willy-JL/F95Checker/assets/45564804/1e61672c-681d-4fbb-8f31-fce6e184d4be)

**Comment by Willy-JL** [comment] 2024-02-02 19:16
You can show the installed or finished (previously called "played" version) by enabling it in the right click menu of the column headers.

Many games are updated probably because before they didn't have a version associated with them, and I fixed a bug with it not getting version info from the thread if it's missing from the dedicated api. Just middle click on the updated icon to make it go away

And yes, the finished checkboxes changed behavior. They now remember what version you marked as finished, similar to how the installed checkbox remembers what version you had installed. They are not simple "yes/no". Check the FAQ on GitHub README for an updated explanation. Basically, now you can make a game as finished, then when you install a future update, it will show as "half finished", because you had finished a previous version, but now you have a newer one installed, meaning more content to play. That's the general idea. It will take some time to adapt your existing list and get the finished version info to a point where it's useful, but it will be worth it.

**Closed by Willy-JL** 2024-02-02 19:16 UTC

**Comment by FaceCrap** [comment] 2024-02-08 13:34
To further show this visually...

![image](https://github.com/Willy-JL/F95Checker/assets/95778718/0c01dcf5-07ef-4da1-ae9f-2e95f8fa44e7)

This image shows two different situations, the top game is one from before 11 beta, the bottom one shows the new situation.
To have the checkboxes show the new behavior, the simplest you can do is to use any sqlite database utility and set the value for the `finished` (the `played` from before 11 beta) field in the games table to whatever if it is currently blank.
As you can see I used an underscore. This will then also make it easier to have the sorting behave in a similar way to 10.x versions because the checkboxes then show the intended behavior.

>Another observation is that all games now have a shootingStar icon at the end of the name. Previously, this icon was associated only with updated games. 
>It might be helpful to distinguish between games that have received updates and those that haven't to provide users with a clearer overview.

The difference is still clear as day. Only updated games have the black-on-yellow star icon. This alone presents a very visible distinction.
